In [1]:
import numpy as np

# NumPy的ndarray:一种多维数组对象

## 创建ndarray

In [2]:
data1 = [6,7.5,8,0,1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
data2 = [[1,2,3,4],[5,6,7,8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
arr2.dtype

dtype('int32')

In [7]:
arr1.dtype

dtype('float64')

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.empty((2,3,2))    #返回的不一定全0数组，而是一些未初始化的垃圾值

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

## ndarray的数据类型

In [15]:
arr1 = np.array([1,2,3],dtype=np.float64)

arr2 = np.array([1,2,3],dtype=np.int32)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
arr = np.array([1,2,3,4,5])

arr.dtype

dtype('int32')

In [19]:
float_arr = arr.astype(np.float64)

float_arr.dtype

dtype('float64')

In [20]:
arr = np.array([3.7,-1.2,2.6,0.5,12.8,10.1])

arr

array([ 3.7, -1.2,  2.6,  0.5, 12.8, 10.1])

In [21]:
arr.astype(np.int32)

array([ 3, -1,  2,  0, 12, 10])

## 数组和标量之间的运算

In [22]:
arr = np.array([[1.,2,3],[4,5,6]])

arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## 基本的索引与切片

In [27]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12

arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [35]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#视图
arr_view = arr[5:8]

arr_view[1] = 99

arr

array([ 0,  1,  2,  3,  4,  5, 99,  7,  8,  9])

In [38]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#副本
arr_copy = arr[5:8].copy()

arr_copy[1] = 99

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr_copy

array([ 5, 99,  7])

In [41]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr2d[2]

array([7, 8, 9])

In [42]:
arr2d[0][2]

3

In [43]:
arr2d[0,2]

3

In [44]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d.shape

(2, 2, 3)

In [46]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr3d[1,0]

array([7, 8, 9])

In [48]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [50]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

## 布尔型索引

In [57]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

data = np.random.randn(7,4)

data

array([[-0.54944519,  0.92602467, -0.46599517, -0.89173482],
       [ 0.34681786, -0.2683059 ,  0.75128226,  1.85602353],
       [ 0.33468605,  1.37769067, -0.64593435, -0.60772167],
       [ 0.73229416,  0.25579332,  0.73139384, -0.29225846],
       [-0.13140623, -0.31660335, -0.13937012,  0.40380991],
       [ 0.28721827,  0.57437958, -0.76008619, -1.19775937],
       [-1.13252428, -0.46288239, -1.89356923, -2.71333673]])

In [58]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [59]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [60]:
data[names=='Bob']

array([[-0.54944519,  0.92602467, -0.46599517, -0.89173482],
       [ 0.73229416,  0.25579332,  0.73139384, -0.29225846]])